# Generated by Django 2.0.7 on 2019-02-16 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='comment',
            new_name='content',
        ),
    ]
