# Generated by Django 2.0.7 on 2019-02-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogg', '0003_auto_20190217_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Content',
            field=models.TextField(default=''),
        ),
    ]
